/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside.vue')['default']
    CategoryEdit: typeof import('./src/components/CategoryEdit.vue')['default']
    GoodsEdit: typeof import('./src/components/GoodsEdit.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
